use formularioEletronico;

INSERT INTO Patologia VALUES (1, "NDA");
INSERT INTO Patologia VALUES (110, "Tuberculose");
INSERT INTO Patologia VALUES (120, "Hanseníase");
INSERT INTO Patologia VALUES (510, "Diabetes Tipo 1");
INSERT INTO Patologia VALUES (511, "Diabetes Tipo 2");
INSERT INTO Patologia VALUES (1100, "Hipertensão");

INSERT INTO ClassificacaoEtaria VALUES (11, "0 a 11 anos", "Criança (0-11)");
INSERT INTO ClassificacaoEtaria VALUES (1217, "12 a 17 anos", "Adolescente (12-17)");
INSERT INTO ClassificacaoEtaria VALUES (1825, "18 a 25 anos", "Jovem Adulto (18-25)");
INSERT INTO ClassificacaoEtaria VALUES (2659, "26 a 59 anos", "Adulto (26-59)");
INSERT INTO ClassificacaoEtaria VALUES (6000, "60 anos adiante", "Idoso (60+)");

INSERT INTO UF VALUES (11, "RO", "Rondônia");
INSERT INTO UF VALUES (12, "AC", "Acre");
INSERT INTO UF VALUES (13, "AM", "Amazonas");
INSERT INTO UF VALUES (14, "RR", "Roraima");
INSERT INTO UF VALUES (15, "PA", "Pará");
INSERT INTO UF VALUES (16, "AP", "Amapá");
INSERT INTO UF VALUES (17, "TO", "Tocantins");
INSERT INTO UF VALUES (21, "MA", "Maranhão");
INSERT INTO UF VALUES (22, "PI", "Piauí");
INSERT INTO UF VALUES (23, "CE", "Ceará");
INSERT INTO UF VALUES (24, "RN", "Rio Grande do Norte");
INSERT INTO UF VALUES (25, "PB", "Paraíba");
INSERT INTO UF VALUES (26, "PE", "Pernambuco");
INSERT INTO UF VALUES (27, "AL", "Alagoas");
INSERT INTO UF VALUES (28, "SE", "Sergipe");
INSERT INTO UF VALUES (29, "BA", "Bahia");
INSERT INTO UF VALUES (31, "MG", "Minas Gerais");
INSERT INTO UF VALUES (32, "ES", "Espírito Santo");
INSERT INTO UF VALUES (33, "RJ", "Rio de Janeiro");
INSERT INTO UF VALUES (35, "SP", "São Paulo");
INSERT INTO UF VALUES (41, "PR", "Paraná");
INSERT INTO UF VALUES (42, "SC", "Santa Catarina");
INSERT INTO UF VALUES (43, "RS", "Rio Grande do Sul");
INSERT INTO UF VALUES (50, "MS", "Mato Grosso do Sul");
INSERT INTO UF VALUES (51, "MT", "Mato Grosso");
INSERT INTO UF VALUES (52, "GO", "Goiás");
INSERT INTO UF VALUES (53, "DF", "Distrito Federal");

INSERT INTO Zona VALUES (1, "Urbana");
INSERT INTO Zona VALUES (2, "Rural");

INSERT INTO Paciente VALUES (1, "Maria da Silva", 6000, "Feminino", "Rua Horus, 378", 1100, true, 35, 1);
INSERT INTO Paciente VALUES (2, "Gabriel Pereira", 1217, "Masculino", "Avenida Santos Dumont, 1072", 510, true, 31, 2);
INSERT INTO Paciente VALUES (3, "Valdemir Barros", 1217, "Masculino", "Rua das Flores, 110", 511, false, 28, 2);
INSERT INTO Paciente VALUES (4, "Flávia Oliveira", 1825, "Feminino", "Rua José Bonifácio, 70", 1, false, 43, 1);
INSERT INTO Paciente VALUES (5, "Simone Lima", 2659, "Feminino", "Rua Raul Júnior, 180", 511, false, 33, 1);
INSERT INTO Paciente VALUES (6, "José Figueira", 6000, "Masculino", "Rua XV de Novembro, 871", 110, true, 33, 1);
INSERT INTO Paciente VALUES (7, "João Santos", 2659, "Masculino", "Avenida Marechal Deodoro, 76", 120, true, 35, 2);
INSERT INTO Paciente VALUES (8, "Marcos Casanova", 1825, "Masculino", "Rua São Carlos, 176", 1, false, 42, 1);
INSERT INTO Paciente VALUES (9, "Helena Dantas", 11, "Feminino", "Rua Faleiros, 38", 1, false, 32, 2);
INSERT INTO Paciente VALUES (10, "Ailton Castro", 2659, "Masculino", "Rua Antônio Carlos, 19", 1100, false, 52, 2);
INSERT INTO Paciente VALUES (11, "Bento Nobre", 1217, "Masculino", "Rua Arlindo Nogueira, 105", 1, true, 16, 1);
INSERT INTO Paciente VALUES (12, "Cátia Brião", 6000, "Feminino", "Rua das Fiandeiras, 50", 110, false, 41, 2);
INSERT INTO Paciente VALUES (13, "Elisa Barreto", 2659, "Feminino", "Rua Domingos Olímpio, 43", 511, false, 11, 1);
INSERT INTO Paciente VALUES (14, "Cláudio Figueiredo", 6000, "Masculino", "Avenida São João, 544", 1100, true, 50, 1);
INSERT INTO Paciente VALUES (15, "Gueda Salazar", 11, "Feminino", "Rua Cândido Portinari, 22", 510, true, 43, 1);
INSERT INTO Paciente VALUES (16, "Heitor Guimaraens", 2659, "Masculino", "Rua dos Carijós, 810", 120, true, 51, 1);
INSERT INTO Paciente VALUES (17, "Iberê Parente", 6000, "Masculino", "Rua Serra de Bragança, 742", 1100, true, 23, 2);
INSERT INTO Paciente VALUES (18, "Jandira Siebra", 1825, "Feminino", "Rua Barão de Vitória, 196", 120, false, 15, 1);
INSERT INTO Paciente VALUES (19, "Nídia Herrera", 6000, "Feminino", "Avenida Afonso Pena, 340", 511, false, 31, 1);
INSERT INTO Paciente VALUES (20, "Rafaela Garrido", 2659, "Feminino", "Rua Pereira Estéfano, 238", 511, true, 53, 2);
INSERT INTO Paciente VALUES (21, "Valéria Guimaraes", 1825, "Feminino", "Travessa Antônio Ferreira, 11", 110, false, 31, 1);
INSERT INTO Paciente VALUES (22, "Jónatas Caminha", 2659, "Masculino", "Rua Cristiano Olsen, 239", 1100, true, 24, 1);
INSERT INTO Paciente VALUES (23, "Luciano Lucena", 1217, "Masculino", "Avenida Maximiano Fonseca, 33", 120, true, 23, 2);
INSERT INTO Paciente VALUES (24, "Flávia Arantes", 1825, "Feminino", "Avenida Esbertalina Damiani, 90", 1, false, 52, 1);
INSERT INTO Paciente VALUES (25, "Débora Assumpção", 2659, "Feminino", "Praça da República, 110", 510, false, 33, 1);
INSERT INTO Paciente VALUES (26, "Gregório Pérez", 6000, "Masculino", "Rua Coronel Cardoso, 132", 510, true, 14, 1);
INSERT INTO Paciente VALUES (27, "Conrado Lameira", 2659, "Masculino", "Rua Frederico Moura, 144", 1, false, 21, 2);
INSERT INTO Paciente VALUES (28, "Luzia Sanches", 6000, "Feminino", "Rodovia Raposo Tavares, 22", 511, true, 32, 2);
INSERT INTO Paciente VALUES (29, "Antônio Mendes", 1825, "Masculino", "Rua Augusto Cornelsen, 550", 1100, true, 35, 1);
INSERT INTO Paciente VALUES (30, "Eliana Souza", 6000, "Feminino", "Avenida Michel Pena, 430", 510, false, 31, 1);